spring:
  application:
    name: deepexi-dubbo
  profiles:
    active: local
  dubbo:
    application:
      name: deepexi-dubbo
    protocol:
      name: dubbo
      port: 20880
    consumer:
      check: false
    registry:
      check: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
swagger:
  base-package: com.deepexi.controller
  info:
    title: deepexi-dubbo
server:
  port: 8080
logging:
  file: 'logs/${spring.application.name}.log'
mybatis:
  mapper-locations: 'classpath:mapper/*.xml'
